language: php
php:
 - 5.6
 - 7.0
 - hhvm

# This helps builds go quicker on Travis since it enables caching of dependencies
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Do not limit history to latest commits. Merge commits will need older commits.
# Limiting depth caused issues with /.scripts/travis/check_commit_msgs.sh
#git:
#  depth: 1

branches:
  except:
    - 1.0
    - 1.5
    - 1.6
    - 1.7
    - 1.8

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

  include:
    # Lint checks for PHP code and composer.json
    - php: 5.6
      env: VARIA=true
      before_install:
        - phpenv config-rm xdebug.ini
      install:
       - phpenv rehash
       - composer travis:install
      script: 
       - composer lint
       
    # Build and test javascript
    - php: 5.6
      env: VARIA=true
      before_install:
        - phpenv config-rm xdebug.ini
      install:
       - npm install
       - composer travis:install
      script:
       - npm test

    # Memcached enabled
    - php: 5.6
      services:
       - memcached
       - mysql
      env: VARIA=true
      before_install:
        - phpenv config-rm xdebug.ini
        - phpenv config-add ./.scripts/travis/memcached.ini
      install:
       - composer travis:install-with-mysql
      script:
       - php -f ./.scripts/is_memcached_enabled.php
       - ./vendor/bin/phpunit --configuration ./.scripts/travis/phpunit-memcached.xml
       - php ./engine/tests/suite.php --config ./.scripts/travis/elgg-config/simpletest_memcached.php

    # End to end tests
    - php: 5.6
      env: E2E=true
      before_install:
        - phpenv config-rm xdebug.ini
      install:
       - composer travis:install-with-mysql
       - php -S localhost:8888 index.php &
       - sleep 3 # give Web server some time to bind to sockets, etc
      script:
       - curl -o - http://localhost:8888/ | grep "<title>Elgg Travis Site</title>"
       - ./vendor/bin/phpunit
       - php -f ./engine/tests/suite.php

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - composer config -g github-oauth.github.com ${GITHUB_TOKEN}

install: composer travis:install-with-mysql

script:
  - ./vendor/bin/phpunit
  - php -f ./engine/tests/suite.php

# mod testing
  - cd ./mod/
  - phpunit


notifications:
  email:
    secure: exC/ws07lLOj3Y43C89jiaKpyB8Yt7DPGSCShV4R3Wkw/hVVzjxt1BinPxzsyL5DC7APUMcTHGOhDB2oCE4ynDE6o6L9bH79fc+V8IYAiNaEIGL0AOuHdnRdGN9GMrr2jv78cZ5MctuUTkeYLaoOEyDGHmkMhqa6SufIDAY8b58=
  webhooks:
    urls:
     - secure: "Ug81+4Fa2UFZetSCV79OWOgYi4uVgNQ6rVrVn2HElddOMDwuHxo9CYKoA3Q+joPKMtNFCN2qkMyoyUfIMM83uJi1LmaUx/c7lR1pXBFVgc4Xyt114NcY80I4OCWWKg0G1FDlSiaXil922JjeC3MekYoqjsIyUgabGihe6j7DWz0="
    on_start: true
  slack: 
     secure: elgg:qUNTV70bSXTkIdr7b4FjvFhm
     on_failure: always
     on_success: never

env:
  global:
     secure: "fdpCjdC0Qp/ZJqtrCHE4I/tHXWF1sORftm6khd6geqK7d4qWzIh6HzNN2BlF+2m4nyuyxo2wzPm/oGoqogVpBgrzpQ7SZl7h2/wzgs2C/k39sFGyDisLesTM5DhBDJWcomyqtcnQmKn340Z9KOxiHAt4FOj2FZVN5+tIO5j3Cks="

## Cache dependencies
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
